version: '3.9'

services:
  postgres:
    image: postgres:13.4
    ports:
      - 5432:5432
    volumes:
      - "~/Documents/Github Projects/basketball-fantasy-mn/game-engine/db/data/:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=game-engine
