version: '3.9'

services:
  game_engine:
    image: game-engine
    container_name: game_engine
    ports:
      - "8080:8080"
    environment:
      datasources.default.url: jdbc:postgresql://game_engine_database:5432/game-engine
    depends_on:
      - game_engine_database

  postgres:
    image: postgres:13.4
    container_name: game_engine_database
    ports:
      - 5432:5432
    volumes:
      - "~/Documents/Github Projects/basketball-fantasy-mn/game-engine/db/data/:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=game-engine
